title: Chanchan's blog
description: Welcome to chanchan's blog
show_downloads: false

baseurl: "/blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://chanchann.github.io/" # change this to the base hostname & protocol for your site

# Math settings
markdown: kramdown
kramdown:
  math_engine: katex
  math_engine_opts:
    preview: true

google_analytics: G-WR5TYD5MZ5  # 替换为你的 GA4 测量 ID

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: jekyll-theme-cayman

# social
author: chanchan
image: /thumbnail-jumbo.png
twitter:
  username: chanchan

plugins:
  - jekyll-target-blank
  - jekyll-katex  # Add KaTeX support

target-blank:
    rel: nofollow

header_page_refs: ['about', 'posts', 'statistics', 'contact']

# GitHub Comments (powered by utteranc.es)
github_comments:
  repository: chanchann/blog-comments # Change this to your GitHub username/repository that will store the comments
